### ISSUE TITLE
Support for nullable?

### ISSUE THREAD

**Issue by pumpkinlink** [Manweill/swagger-axios-codegen#31]
Does this codegen support translating swagger [nullable](https://swagger.io/docs/specification/data-models/data-types/#null) data type attribute as typescript undefined/null/question mark?

**Comment by Manweill** [comment]
For example ？

**Comment by Manweill** [comment]
@pumpkinlink  
You can set `strictNullChecks = false`

**Comment by Manweill** [comment]
@pumpkinlink 
Yes, I will accept if it is reasonable. Wellcome~

**Comment by joshstrange** [comment]
@Manweill Thank you for this library! I was wondering how you think would be best to address this. Not sure if you want the `IPropDef` updated to have another property of `nullable: boolean` or we can re-used the `validationModel` property. Doing a little surgical editing I took this line:

        ${props.map(p => classPropsTemplate(p.name, p.type, p.format, p.desc, !strictNullChecks, false, false)).join('')}

to

        ${props.map(p => classPropsTemplate(p.name, p.type, p.format, p.desc, !strictNullChecks || !p.validationModel || !p.validationModel.required, false, false)).join('')}

The difference being the addition of `!p.validationModel || !p.validationModel.required` along with `!strictNullChecks`. 

Since in my testing I was seeing `p.validationModel` be either `null` or `validationModel: { required: true }`. Now that's just with my schema so I'm not sure what else might be in there for other people.

This change gave me the behavior I was looking for (nullable properties now have the '?' on them). I'm happy to put together a pull request for just that change to the interface/class code. Let me if that is acceptable or if you were looking for something bigger/different. 

All that said my gut feeling is even this isn't the best approach or should be behind a flag (`nullableBehavior: 'optional' | 'null-type' | 'both'`). I think I would prefer to have the type written out like `myProp: string | null` (assuming `myProp` was a string in Swagger). But I can understand some people might want the `?` added as well so they don't even have to define it as null to pass type checks. Let me know your thoughts.

**Comment by Manweill** [comment]
like this:
`myProp:string|null|undefined`

**Comment by LuccaPrado** [comment]
Any update to that?

**Comment by pumpkinlink** [comment]
> Any update to that?

In my case I'm unfortunately no longer working on the project I mentioned, so don't expect a PR from me anymore, at least on the foreseeable future... :/
